### ISSUE TITLE
Hello. I need help :)

### ISSUE THREAD

**Issue by mefilt** [NoTests/RxFeedback.swift#35]
I use RxFeedback in the project, but I have a problem and I can not solve it either. And most likely it's from a lack of knowledge.
I use "methodInvoked (#selector (UIViewController.viewWillAppear (_ :)))" and send the "readyView" event to the system.
But "methodInvoked" does not send element to the system, but if you subscribe without the system, everything is fine.
And if the UIViewController.viewWillAppear method is repeatedly called, then the message comes through.

Here is an example
https://github.com/mefilt/RxFeedbackTest/blob/master/RxFeedbackTest/ViewController.swift

Thx

**Comment by eliekarouz** [comment]
I encountered a similar issue when building a bluetooth system that I start on application launch. The system was monitoring the methodInvoked stream for appDidBecomeActive but it seems to me that the system was missing the first event due to the async nature of the architecture. So it subscribed right after the method was invoked. @kzaher is this a correct behavior?
It doesn't happen on all devices/iOS versions though. 

I solved it by using a BehaviorRelay instead of the methodInvoked. I update the variable in viewWillAppear and viewWillDisappear and the system gets notified and will not miss the event. I think it makes sense as it's more like a state rather than just a Signal that you need.

**Comment by kzaher** [comment]
This is reliance on the timing of the subscription. This is quite fragile approach IMHO. Subscribing to a state describing is the VC view visible is better IMHO.
