### ISSUE TITLE
How can I fix this warning

### ISSUE THREAD

**Issue by nizenyang** [NoTests/RxFeedback.swift#51]
![image](https://user-images.githubusercontent.com/8390188/56330779-30ae8380-61bc-11e9-88d5-2afdfb7f949d.png)
please help me how can i fix this warning
thank you

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
